	var lypmenucount=4;												//菜单数量
	OB_Top=0;															//菜单距离顶部的象素值；
	OB_Left=0;														//菜单距离左侧的象素值；
	OB_Margin=5;													//top and bottom margins between icons and borders
	OB_Width=100;													//菜单宽度
	OB_Height=document.body.clientHeight;	//菜单高度
	OB_SlideSpeed=10;											//菜单运动速度
	OB_BackgroundColor="AAA8A4";					//背景色

	OB_ItemsSpacing=17;										//2个图标间的距离
	OB_BorderWidth=5;											//border宽度
	OB_BorderStyle="solid";								//border风格
	//OB_BorderStyle="ridge";
	OB_BorderColor="D0D0D0";							//border颜色
	OB_IconsWidth=25;											//图标宽度
	OB_IconsHeight=25;										//图标高度
	OB_ButtonFontFamily="宋体";						//按钮上字体的字型
	OB_ButtonFontSize=9;									//按钮上字体大小 
	OB_ButtonFontColor="black";						//按钮上字体颜色    
	OB_ButtonHeight=25;										//按钮的高度
	OB_LabelFontFamily="宋体";							//LOGO下字体的字型
	OB_LabelFontSize=9;										//LOGO下面的字体大小
	OB_LabelFontColor="000000";						//LOGO下的字体颜色
	OB_LabelMargin=3;											//margin between labels and icons
	OB_UpArrow="/Images/Menu/arrowup1.gif";				//向上滚动的logo箭头	
	OB_DownArrow="/Images/Menu/arrowdown1.gif";		//向下滚动的logo箭头
	OB_ArrowWidth=16;											//箭头的宽度
	OB_ArrowHeight=16;										//箭头的高度
	OB_ArrowSlideSpeed=60;								//项目列表滚动的速度；
